# Shruthi Pachava - G01459580
# Harika Gaddam - G01449863
# Akshitha Theretupally - G01472457
# Vamsi Krishna Maram - G01478991

# Kubernetes deployment file for cluster1 using docker image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveyform-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: surveyform-springboot
  template:
    metadata:
      labels:
        app: surveyform-springboot
    spec:
      containers:
        - name: surveyform-springboot-container
          image: atheretu/swe645:latest
          ports:
            - containerPort: 8080
